In [8]:
import numpy as np

In [9]:
daily_sales=np.array([10,30,40,50,60])

In [10]:
new=daily_sales+2
print(new)

[12 32 42 52 62]


In [11]:
cost_price=np.array([2,3,4,5,6])
revenue=np.array(cost_price*daily_sales)
print(revenue)

[ 20  90 160 250 360]


In [12]:
print(np.sqrt(revenue))

[ 4.47213595  9.48683298 12.64911064 15.8113883  18.97366596]
