In [ ]:
import numpy as np

In [ ]:
arr=np.random.randint(120,650,size=(4,7))
print(arr)

[[597 281 286 367 381 213 551]
 [584 274 636 368 159 243 580]
 [143 490 335 199 309 372 269]
 [217 381 539 132 515 380 178]]


In [ ]:
print(arr.shape)

(4, 7)


In [ ]:
print(arr.ndim)

2


In [ ]:
print(arr.size)

28


In [ ]:
print(type(arr))

<class 'numpy.ndarray'>


In [ ]:
avg=np.mean(arr)
print(avg)

356.39285714285717


In [ ]:
avg_per_hostel=np.mean(arr,axis=1)
print(avg_per_hostel)

[382.28571429 406.28571429 302.42857143 334.57142857]


In [ ]:
max_value = np.max(arr)
print(max_value)

636


In [ ]:
max_per_hostel = np.max(arr, axis=1)
print(max_per_hostel)

[597 636 490 539]


In [ ]:
total_per_hostel = np.sum(arr, axis=1)
print(total_per_hostel)

highest_hostel = np.argmax(total_per_hostel)
print( highest_hostel)


[2676 2844 2117 2342]
1


In [ ]:
total_per_day = np.sum(arr, axis=0)
print(total_per_day)


[1541 1426 1796 1066 1364 1208 1578]


In [ ]:
highest_day_index = np.argmax(total_per_day)
print( highest_day_index)


2


In [ ]:
penalized_usage = np.where(arr > 550, arr * 1.20, arr)
print(penalized_usage)


[[716.4 281.  286.  367.  381.  213.  661.2]
 [700.8 274.  763.2 368.  159.  243.  696. ]
 [143.  490.  335.  199.  309.  372.  269. ]
 [217.  381.  539.  132.  515.  380.  178. ]]


Task D : Compare each hostel's daily usage with its own weekly average. Create a boolean matrix where:
True: Above hostel average
False: Below or equal to hostel average

In [ ]:
boolean_matrix=arr>avg_per_hostel[:, np.newaxis]
print(boolean_matrix)

[[ True False False False False False  True]
 [ True False  True False False False  True]
 [False  True  True False  True  True False]
 [False  True  True False  True  True False]]


Task E1: Reshape the electricity data into a single row representing weekly usage(Shape: 1x28)

In [ ]:
single_row=arr.reshape(1,28)
print(single_row)

[[597 281 286 367 381 213 551 584 274 636 368 159 243 580 143 490 335 199
  309 372 269 217 381 539 132 515 380 178]]


Task E2: Reshape the same data into 2 rows and 14 columns. Ensure no data is lost or duplicated.

In [ ]:
two_row=arr.reshape(2,14)
print(two_row)

[[597 281 286 367 381 213 551 584 274 636 368 159 243 580]
 [143 490 335 199 309 372 269 217 381 539 132 515 380 178]]


Task F1:Copy vs View
1.Create ref_backup=electricity
2.Create safe_backup=electricity.copy()
3.Modify one value in the original electricity array
4.Observe which backups change

In [ ]:
ref_backup=arr
safe_backup=arr.copy()
arr[0][0]=999
print(ref_backup)
print(safe_backup)
print(arr)

[[999 281 286 367 381 213 551]
 [584 274 636 368 159 243 580]
 [143 490 335 199 309 372 269]
 [217 381 539 132 515 380 178]]
[[597 281 286 367 381 213 551]
 [584 274 636 368 159 243 580]
 [143 490 335 199 309 372 269]
 [217 381 539 132 515 380 178]]
[[999 281 286 367 381 213 551]
 [584 274 636 368 159 243 580]
 [143 490 335 199 309 372 269]
 [217 381 539 132 515 380 178]]
