In [1]:
!pip install numpy



[notice] A new release of pip is available: 23.0.1 -> 26.0.1
[notice] To update, run: C:\Users\vansh\AppData\Local\Programs\Python\Python310\python.exe -m pip install --upgrade pip


In [2]:
import numpy as np

In [3]:
arr=np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [4]:
mat=np.array([[1,3,4],[5,6,7]])
print(mat)

[[1 3 4]
 [5 6 7]]


In [5]:
np.zeros(5)


array([0., 0., 0., 0., 0.])

In [6]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [7]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [8]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

Range of numbers

In [9]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

Evenly spaced numbers

In [11]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

Array properties

In [12]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr.ndim) #dimensions
print(arr.shape) #rows, columns
print(arr.size) #total elements
print(arr.dtype) #data type

2
(2, 3)
6
int64


Type  conversion

In [13]:
arr=np.array([1.2,2.5,3.7])
arr_int=arr.astype(int)
print(arr_int)

[1 2 3]


Indexing and Slicing

In [14]:
arr=np.array([10,20,30,40])
print(arr[0])
print(arr[-1])

10
40


1D slicing

In [15]:
print(arr[1:3])
print(arr[:2])
print(arr[::2])

[20 30]
[10 20]
[10 30]


2D Indexing

In [16]:
mat=np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
print(mat[0,1])
print(mat[1])

2
[4 5 6]


In [17]:
print(mat[:,1]) #column1

[2 5 8]


Copy function - we use this bcz if we directly copy like this b=a then the original array will be changed but by using copy function original remains unaffected

In [18]:
a=np.array([1,2,3])
b=a.copy()#this logic is safe
b[0]=99
print(a)
print(b)

[1 2 3]
[99  2  3]


In [19]:
a=np.array([1,2,3])
b=a
b[0]=99
print(a)#this logic is not safe
print(b)


[99  2  3]
[99  2  3]


Basic Mathematical Operations

In [20]:
a=np.array([1,2,3])
b=np.array([4,5,6])

In [21]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


Scalar Operations

In [22]:
print(a+10)
print(a*2)

[11 12 13]
[2 4 6]


Unfus (Universal Functions)

In [23]:
arr=np.array([1,4,9,16])
print(np.sqrt(arr))
print(np.log(arr))
print(np.exp(arr))
print(np.max(arr))
print(np.min(arr))
print(np.mean(arr))
print(np.sum(arr))
print(np.std(arr))

[1. 2. 3. 4.]
[0.         1.38629436 2.19722458 2.77258872]
[2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06]
16
1
7.5
30
5.678908345800274


Boolean Indexing

In [24]:
arr=np.array([10,20,30,40,50])
print(arr[arr>25])

[30 40 50]


In [25]:
print(arr>25)

[False False  True  True  True]


Broadcasting Rule

In [26]:
#Numpy automatically expands smaller
arr=np.array([1,2,3,4,5,6])
print(arr+10)



[11 12 13 14 15 16]


In [27]:
mat=np.array([[1,2,3],
              [4,5,6]])
print(mat+10)

[[11 12 13]
 [14 15 16]]


In [28]:
row=np.array([1,2,3])
print(mat+row)

[[2 4 6]
 [5 7 9]]


Matrix Multiplication

In [29]:
A=np.array([[1,2],
            [3,4]])
B=np.array([[5,6],
            [7,8]])
print(np.dot(A,B))
# IF we do not write dot it thinks it is a element wise multiplication

[[19 22]
 [43 50]]


In [30]:
print(A.T) #Transpose

[[1 3]
 [2 4]]


Random Module

In [31]:
np.random.rand(3,3)

array([[0.92737886, 0.09638489, 0.22582144],
       [0.34679343, 0.14527584, 0.5192041 ],
       [0.36258836, 0.50216614, 0.04494556]])

In [32]:
np.random.rand(5)

array([0.00191958, 0.52672487, 0.9483425 , 0.74431407, 0.01339651])

In [33]:
np.random.randint(1,100,10)

array([99, 80, 36, 51, 74, 55, 14, 95, 48, 98], dtype=int32)

Reshaping Arrays

In [34]:
arr=np.arange(12) #range should be between 0 to 11
print(arr.reshape(3,4))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


Axis in NumPy

In [35]:
import numpy as np
arr=np.array([[1,2,3],
              [4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [36]:
print(np.sum(arr))

21


In [37]:
print(np.sum(arr,axis=0)) #column wise


[5 7 9]


In [38]:
print(np.sum(arr,axis=1)) #row wise

[ 6 15]


Where in numpy

In [39]:
arr=np.array([10,-5,20,-3,15])

In [40]:
result=np.where(arr<0,0,arr)
print(result)

[10  0 20  0 15]


In [41]:
arr=np.array([1,2,3,4,5])
result=np.where(arr%2!=0,-1,arr)
print(result)

[-1  2 -1  4 -1]


In [42]:
marks=np.array([10,80,20,45,50])
status=np.where(marks>=50,1,0)
print(status)

[0 1 0 0 1]


In [43]:
data=np.array([10,20,30,40,50])
mean_val=np.mean(data)
result=np.where(data>mean_val,mean_val,data)
print(result)

[10. 20. 30. 30. 30.]


Applying (where) condition in 2d array

In [44]:
mat=np.array([[10,60,30],
              [80,20,90]])

In [45]:
result=np.where(mat>50,1,0)
print(result)

[[0 1 0]
 [1 0 1]]
